### ISSUE TITLE
显示有问题

### ISSUE THREAD

**Issue by lvxiangan** [congxc/WeChartPullToRefreshListView#1]
操作步骤：
1、手指先向上拖动，加载更多，加载多几十条，使得scrollview滑到底部。
2、手指按住屏幕向下拉（往回拖动查看最上面如第10条），未达到顶部却会显示“释放立刻刷新”。

**Comment by ddwhan0123** [comment]
I find the same question

**Comment by congxc** [comment]
isLower 与isUpper未赋值导致此问题，详情请查看utils/refreshLoadRegister.js
