### ISSUE TITLE
大神求教

### ISSUE THREAD

**Issue by wendesun** [congxc/WeChartPullToRefreshListView#2]
<scroll-view class="scroll_container" scroll-y="true" style="position:fixed;width:100%;left:0;height:{{windowHeight}}px;top:{{loadMoreHeight == 0? refreshHeight:-loadMoreHeight}}px;bottom:{{loadMoreHeight}}px;"  bindscroll="scroll" bindscrolltolower="lower" bindscrolltoupper="upper" bindtouchstart="start" bindtouchend="end" > 
    <view style="width:100%;height:100%" bindtouchmove="move">
        <block wx:for="{{words}}">  
                <view class="item-style">{{item}}</view>  
        </block>  
    </view>
</scroll-view>
----------------------------------------上面是原代码----------------------------------------
 <view style="width:100%;height:100%" bindtouchmove="move"> 请问下，为什么要套这一层，这个touchmove放在scroll-view上不可以吗？

**Comment by wendesun** [comment]
> {{item}} ----------------------------------------上面是原代码---------------------------------------- 请问下，为什么要套这一层，这个touchmove放在scroll-view上不可以吗？

**Comment by congxc** [comment]
嗯，不可以，你可以理解为因为外层scroll view实际上已经实现其touchmove事件了，也就是滚动事件，我们不能对其做修改。
  最后我只是一个普通的Android开发员，这个例子也只是因为当初领导临时要求做一个微信小程序而顺带写的而已，“大神”二字实在不敢当

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wendesun <notifications@github.com>
发送时间: 2018年9月27日 17:25
收件人: congxc/WeChartPullToRefreshListView <WeChartPullToRefreshListView@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[congxc/WeChartPullToRefreshListView] 大神求教 (#2)

{{item}} ----------------------------------------上面是原代码---------------------------------------- 请问下，为什么要套这一层，这个touchmove放在scroll-view上不可以吗？
